window.HANNANS_IMPORTED_BOOKINGS = {
  "source": "C:\\Users\\Jess Malec\\Dropbox\\Hannans Club\\Club Operations\\Events\\Event Bookings_2026\\BOOKINGS_2026.xlsx",
  "importedAt": "2026-06-17",
  "count": 60,
  "bookings": [
    {
      "id": "BK26-001",
      "client": "stephanie.johnson@netballwa.com.au",
      "eventName": "Netball Sundowner",
      "date": "2026-02-26",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 80,
      "start": "7:00 PM",
      "finish": "9:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Sarah Hughes:\n80 pax\n7-9pm approx\nstephanie.johnson@netballwa.com.au\nTENTATIVELY BOOKED",
      "contactEmail": "stephanie.johnson@netballwa.com.au",
      "contactPhone": "",
      "sourceCell": "AA16"
    },
    {
      "id": "BK26-002",
      "client": "TBA",
      "eventName": "Jeff Jones Wake",
      "date": "2026-03-05",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 100,
      "start": "11:00 AM",
      "finish": "3:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Ted to Organise\n100 pax\n11am - 3pm approx\nRaj doing platters",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "F27"
    },
    {
      "id": "BK26-003",
      "client": "jess.garwood25@gmail.com",
      "eventName": "Jessica & David Garwood",
      "date": "2026-03-07",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 30,
      "start": "2:00 PM",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Jess Garwood\njess.garwood25@gmail.com\n0417956000\nBaby Celebration\n30 pax\n2pm - TBA\nSelf catering",
      "contactEmail": "jess.garwood25@gmail.com",
      "contactPhone": "0417956000",
      "sourceCell": "H27"
    },
    {
      "id": "BK26-004",
      "client": "TBA",
      "eventName": "St Patricks Day \nClubs function",
      "date": "2026-03-17",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "R27"
    },
    {
      "id": "BK26-005",
      "client": "TBA",
      "eventName": "Meat raffle\nClubs function",
      "date": "2026-03-20",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "U27"
    },
    {
      "id": "BK26-006",
      "client": "TBA",
      "eventName": "Goldifelds Footbal League Season Lauch - TBC",
      "date": "2026-03-29",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AD27"
    },
    {
      "id": "BK26-007",
      "client": "TBA",
      "eventName": "Raj Lunch",
      "date": "2026-03-15",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "P28"
    },
    {
      "id": "BK26-008",
      "client": "administratorkal@curtin.edu.au",
      "eventName": "Curtin University",
      "date": "2026-03-12",
      "roomId": "billards-room",
      "roomName": "The Billards Room",
      "guests": 70,
      "start": "5:00 PM",
      "finish": "11:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Rachel Neighbour\n5-11pm - 50-70pax\nDiscussing with Raj re catering\nadministratorkal@curtin.edu.au\n08 9088 6173\nbar tab: $1000",
      "contactEmail": "administratorkal@curtin.edu.au",
      "contactPhone": "08 9088 6173",
      "sourceCell": "M29"
    },
    {
      "id": "BK26-009",
      "client": "TBA",
      "eventName": "GOOD FRIDAY PUBLIC HOLIDAY",
      "date": "2026-04-03",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "D38"
    },
    {
      "id": "BK26-010",
      "client": "TBA",
      "eventName": "EASTER MONDAY PUBLIC HOLIDAY",
      "date": "2026-04-06",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "G38"
    },
    {
      "id": "BK26-011",
      "client": "TBA",
      "eventName": "Baby shower",
      "date": "2026-04-12",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 30,
      "start": "10:00 AM",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Ben de Bruyn\n30 pax\n10 AM till TBA\nRaj Catering",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "M38"
    },
    {
      "id": "BK26-012",
      "client": "TBA",
      "eventName": "ANZAC DAY PUBLIC HOLIDAY",
      "date": "2026-04-25",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "Z38"
    },
    {
      "id": "BK26-013",
      "client": "TBA",
      "eventName": "Restaurant booking - 25 pax",
      "date": "2026-04-29",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 25,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AD39"
    },
    {
      "id": "BK26-014",
      "client": "slade.b.hayward@gmail.com",
      "eventName": "Slade Hayward Wake",
      "date": "2026-05-08",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 60,
      "start": "3:30 PM",
      "finish": "7:30 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Slade Hayward\n0448575356\nslade.b.hayward@gmail.com\n60 pax confirmed\nRaj catering\n3:30 -7:30pm",
      "contactEmail": "slade.b.hayward@gmail.com",
      "contactPhone": "0448575356",
      "sourceCell": "I50"
    },
    {
      "id": "BK26-015",
      "client": "eventassist@kbcci.com.au",
      "eventName": "KBCCI",
      "date": "2026-05-20",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 90,
      "start": "1:00 ",
      "finish": "6:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Babita Gurug (KBCCI)\n9021 2466\n0499 647 939\neventassist@kbcci.com.au\n85-90 pax\nSet up from 3:30pm\n5:30pm-7:30pm\nRaj catering\nTab on the night - house beer/wine & soft drink\nTables to be moved away from doorway to alfresco area\nInvoiced - INV1703",
      "contactEmail": "eventassist@kbcci.com.au",
      "contactPhone": "021 2466",
      "sourceCell": "U50"
    },
    {
      "id": "BK26-016",
      "client": "Maritac.holdaway@yahoo.com.au",
      "eventName": "Night of the Muses",
      "date": "2026-05-23",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 80,
      "start": "6:00 PM",
      "finish": "10:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Marita Holdaway\n0437 554 442\nMaritac.holdaway@yahoo.com.au\nLocal emerging talent\n80 pax TBC\nBump in 3pm\nOpen from 6pm - 10pm\nVenue hire waived\nINV-1754",
      "contactEmail": "Maritac.holdaway@yahoo.com.au",
      "contactPhone": "0437 554 442",
      "sourceCell": "X50"
    },
    {
      "id": "BK26-017",
      "client": "bill@mckenzielawyers.com.au",
      "eventName": "Carmels 70th Birthday",
      "date": "2026-05-24",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 40,
      "start": "6:00 ",
      "finish": "4:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Bill Mckenzie\n0418913545\nbill@mckenzielawyers.com.au\n30-40 pax\n70th Birthday\n1pm - 4pm\nRaj Catering\nBar Tab\nINV-1753",
      "contactEmail": "bill@mckenzielawyers.com.au",
      "contactPhone": "0418913545",
      "sourceCell": "Y50"
    },
    {
      "id": "BK26-018",
      "client": "Veronica_lofthouse@outlook.com",
      "eventName": "Veronica Lofthouse",
      "date": "2026-05-30",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 50,
      "start": "5:00 PM",
      "finish": "10:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Veronica Lofthouse Birthday\n0417725310\nVeronica_lofthouse@outlook.com\n50 pax TBC\n5pm - 10pm",
      "contactEmail": "Veronica_lofthouse@outlook.com",
      "contactPhone": "0417725310",
      "sourceCell": "AE50"
    },
    {
      "id": "BK26-019",
      "client": "nicoleruly@gmail.com",
      "eventName": "Hockey Club",
      "date": "2026-05-31",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "11:00 AM",
      "finish": "2:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Norths Wesley Hockey Club\nNicole Foo\n0438842741\nnicoleruly@gmail.com\n30 adults\n22 children (mostly under 10)\nFamily Function\nBouncy Castle - HC arranged & invoicing\n11am-2pm\nBrent Kail Member\nInvoices - INV-\nStaff: em + mel\nBringing pizzas",
      "contactEmail": "nicoleruly@gmail.com",
      "contactPhone": "0438842741",
      "sourceCell": "AF50"
    },
    {
      "id": "BK26-020",
      "client": "TBA",
      "eventName": "Restaurant booking - Rotary Club - 20 pax",
      "date": "2026-05-06",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 20,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "G51"
    },
    {
      "id": "BK26-021",
      "client": "TBA",
      "eventName": "Ladies Brunch",
      "date": "2026-05-10",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "K51"
    },
    {
      "id": "BK26-022",
      "client": "boticara@bigpond.com",
      "eventName": "Helloworld Info Night",
      "date": "2026-05-19",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 40,
      "start": "5:00 PM",
      "finish": "7:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Deborah Botica\n0423264016\nboticara@bigpond.com\n40 pax approx\n5pm - 7pm\nExternal catering\nINV-1745\n$300 on bar tab. TBC on night",
      "contactEmail": "boticara@bigpond.com",
      "contactPhone": "0423264016",
      "sourceCell": "T51"
    },
    {
      "id": "BK26-023",
      "client": "TBA",
      "eventName": "Committee Meeting",
      "date": "2026-05-18",
      "roomId": "library",
      "roomName": "Library",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "From 5:30pm",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "S54"
    },
    {
      "id": "BK26-024",
      "client": "TBA",
      "eventName": "WA DAY PUBLIC HOLIDAY",
      "date": "2026-06-01",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "B62"
    },
    {
      "id": "BK26-025",
      "client": "TBA",
      "eventName": "HC Open Night",
      "date": "2026-06-05",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "F62"
    },
    {
      "id": "BK26-026",
      "client": "deborah.kalgoorlie@helloworld.com.au",
      "eventName": "Helloworld",
      "date": "2026-06-23",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 30,
      "start": "6:00 PM",
      "finish": "8:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Debi Botica\ndeborah.kalgoorlie@helloworld.com.au\n0423264016\nTravel Info Evening\n6-8pm\n30pax approx",
      "contactEmail": "deborah.kalgoorlie@helloworld.com.au",
      "contactPhone": "0423264016",
      "sourceCell": "X62"
    },
    {
      "id": "BK26-027",
      "client": "0438900383",
      "eventName": "Phils 60th birthday",
      "date": "2026-06-27",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 100,
      "start": "6:00 PM",
      "finish": "12:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Jenny Edwards\n0438900383\n100 pax\n6pm - 12pm\nBar Tab - house beer/wine & soft drinks\nINV-1748",
      "contactEmail": "",
      "contactPhone": "0438900383",
      "sourceCell": "AB62"
    },
    {
      "id": "BK26-028",
      "client": "Larr.rose@rfdswa.com.au",
      "eventName": "Eastern Goldfields Auxiliary 60th Anniversary",
      "date": "2026-06-29",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 60,
      "start": "5:00 PM",
      "finish": "7:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Larr Rose - RFDS\n08 94176400\nLarr.rose@rfdswa.com.au\n60th Anniversary\n60 pax\n5pm-7pm\nBar tab",
      "contactEmail": "Larr.rose@rfdswa.com.au",
      "contactPhone": "08 94176400",
      "sourceCell": "AD63"
    },
    {
      "id": "BK26-029",
      "client": "c.cole@cmewa.com",
      "eventName": "Chamber of Minerals & Energy",
      "date": "2026-06-25",
      "roomId": "billards-room",
      "roomName": "The Billards Room",
      "guests": 50,
      "start": "5:30 PM",
      "finish": "7:30 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Carolyne Cole\n0437 734 254\nc.cole@cmewa.com\n5:30-7:30pm\n50 pax\nSundowner with guest speaker\nBar Tab - advise when reaches $1500\nMicrophone & Lecturn",
      "contactEmail": "c.cole@cmewa.com",
      "contactPhone": "0437 734 254",
      "sourceCell": "Z64"
    },
    {
      "id": "BK26-030",
      "client": "Kelly.Haddrick@rfdswa.com.au",
      "eventName": "RFDS",
      "date": "2026-06-30",
      "roomId": "billards-room",
      "roomName": "The Billards Room",
      "guests": 100,
      "start": "10:00 ",
      "finish": "10:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Kelly Haddick\nKelly.Haddrick@rfdswa.com.au\n70-100 pax\nRFDS Community Conversation\n4:30pm - 7pm\nRaj catering finger food\nGuests pay their own drinks",
      "contactEmail": "Kelly.Haddrick@rfdswa.com.au",
      "contactPhone": "",
      "sourceCell": "AE64"
    },
    {
      "id": "BK26-031",
      "client": "natalie.grinceri@westernroads.com.au",
      "eventName": "Western Roads Sundowner",
      "date": "2026-07-01",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 70,
      "start": "5:00 PM",
      "finish": "7:30 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Natalie Grinceri\nnatalie.grinceri@westernroads.com.au\nWestern Roads/CRTafe Heavy Vehicle Driving Sundowner\nAssuming:\n5-7:30pm\n60-70pax\nPizza?\nDeposit already paid - INV-1639\nVenue Hire $500\nSocial Membership $55",
      "contactEmail": "natalie.grinceri@westernroads.com.au",
      "contactPhone": "",
      "sourceCell": "B74"
    },
    {
      "id": "BK26-032",
      "client": "eventassist@kbcci.com.au",
      "eventName": "KBCCI",
      "date": "2026-07-17",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 90,
      "start": "1:00 ",
      "finish": "6:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Babita Gurug (KBCCI)\n9021 2466\n0499 647 939\neventassist@kbcci.com.au\n85-90 pax\n5:30pm-7:30pm\nNo catering\nPay for own drinks\nInvoiced - INV1704",
      "contactEmail": "eventassist@kbcci.com.au",
      "contactPhone": "021 2466",
      "sourceCell": "R74"
    },
    {
      "id": "BK26-033",
      "client": "jordan@goldencitymotors.com.au",
      "eventName": "Jordan & Heidi's Wedding",
      "date": "2026-07-18",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 60,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Jordan Dalley (more details to come)\nWedding\nApprox 60pax\nCocktail\njordan@goldencitymotors.com.au\n0476766129\nInvoiced & Paid - INV1700",
      "contactEmail": "jordan@goldencitymotors.com.au",
      "contactPhone": "0476766129",
      "sourceCell": "S74"
    },
    {
      "id": "BK26-034",
      "client": "linnea@kalsigns.com.au",
      "eventName": "Kalsigns Xmas in July",
      "date": "2026-07-24",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 40,
      "start": "3:00 PM",
      "finish": "7:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Linnea Hedblom/John Bruce\n0431157610\nlinnea@kalsigns.com.au\n40 pax\n3pm - 7pm\nRaj Catering",
      "contactEmail": "linnea@kalsigns.com.au",
      "contactPhone": "0431157610",
      "sourceCell": "Y74"
    },
    {
      "id": "BK26-035",
      "client": "deborah.alderdice@macquarie.com",
      "eventName": "MACQUARIE Dinner",
      "date": "2026-08-03",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 280,
      "start": "6:00 PM",
      "finish": "10:30 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Debi Alderdice\n0409114337\ndeborah.alderdice@macquarie.com\n6pm - 10:30pm\nBump in 3pm\nMain Bar and entire outside area\n280 pax approx\nMore details in emails",
      "contactEmail": "deborah.alderdice@macquarie.com",
      "contactPhone": "0409114337",
      "sourceCell": "D87"
    },
    {
      "id": "BK26-036",
      "client": "hjessop@bellpotter.com.au",
      "eventName": "Bell Potter",
      "date": "2026-08-04",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 100,
      "start": "5:00 PM",
      "finish": "7:30 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Holly Jessop\nBell Potter Securities\n0448981899\nhjessop@bellpotter.com.au\n100 pax\n5-7:30pm\nRaj Catering",
      "contactEmail": "hjessop@bellpotter.com.au",
      "contactPhone": "0448981899",
      "sourceCell": "E87"
    },
    {
      "id": "BK26-037",
      "client": "brian.dance@police.wa.gov.au",
      "eventName": "Gold/\nEsp Police",
      "date": "2026-08-19",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 45,
      "start": "4:00 ",
      "finish": "9:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Sarah Hughes:\nBrian Dance\n08 90938450\nbrian.dance@police.wa.gov.au\n40-45 people\n1730 - 2200",
      "contactEmail": "brian.dance@police.wa.gov.au",
      "contactPhone": "08 90938450",
      "sourceCell": "T87"
    },
    {
      "id": "BK26-038",
      "client": "eventassist@kbcci.com.au",
      "eventName": "KBCCI",
      "date": "2026-08-20",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 90,
      "start": "1:00 ",
      "finish": "6:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Babita Gurug (KBCCI)\n9021 2466\n0499 647 939\neventassist@kbcci.com.au\n85-90 pax\n5:30pm-7:30pm\nNo catering\nPay for own drinks",
      "contactEmail": "eventassist@kbcci.com.au",
      "contactPhone": "021 2466",
      "sourceCell": "U87"
    },
    {
      "id": "BK26-039",
      "client": "sharonhoysted@wildcatresources.com.au",
      "eventName": "Wildcat Resources Lunch",
      "date": "2026-08-04",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 40,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Sharon Hoysted\nsharonhoysted@wildcatresources.com.au\n0408 918 277\n40 pax\n12:15-tbc",
      "contactEmail": "sharonhoysted@wildcatresources.com.au",
      "contactPhone": "0408 918 277",
      "sourceCell": "E88"
    },
    {
      "id": "BK26-040",
      "client": "brian.dance@police.wa.gov.au",
      "eventName": "Gold/\nEsp Police",
      "date": "2026-08-19",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 45,
      "start": "4:00 ",
      "finish": "9:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Sarah Hughes:\nBrian Dance\n08 90938450\nbrian.dance@police.wa.gov.au\n40-45 people\n1730 - 2200",
      "contactEmail": "brian.dance@police.wa.gov.au",
      "contactPhone": "08 90938450",
      "sourceCell": "T88"
    },
    {
      "id": "BK26-041",
      "client": "mramshaw@argonaut.com",
      "eventName": "Argonaut Lunch",
      "date": "2026-08-03",
      "roomId": "library",
      "roomName": "Library",
      "guests": 20,
      "start": "12:00 PM",
      "finish": "3:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Meg Ramshaw\nmramshaw@argonaut.com\n0422872785\n20 pax TBC\n12-3pm\nLunch\nRESERVED TV",
      "contactEmail": "mramshaw@argonaut.com",
      "contactPhone": "0422872785",
      "sourceCell": "D91"
    },
    {
      "id": "BK26-042",
      "client": "0400368702",
      "eventName": "Kat O'Flaherty Birthday",
      "date": "2026-09-19",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 150,
      "start": "5:00 PM",
      "finish": "12:00 AM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Kat O’Flaberty\nBirthday 16th and 18th\n150 pax\n5pm-12am\n0400368702\nOrder in 4 cartons of Raspberry Cruisers.",
      "contactEmail": "",
      "contactPhone": "0400368702",
      "sourceCell": "T97"
    },
    {
      "id": "BK26-043",
      "client": "TBA",
      "eventName": "KINGS BIRTHDAY PUBLIC HOLIDAY",
      "date": "2026-09-28",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AC97"
    },
    {
      "id": "BK26-044",
      "client": "0408903319",
      "eventName": "The Round Inc",
      "date": "2026-09-30",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 300,
      "start": "2:00 ",
      "finish": "6:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Raelene Hutchinson\n0408903319\n250-300pax\nMore info tbc",
      "contactEmail": "",
      "contactPhone": "0408903319",
      "sourceCell": "AE97"
    },
    {
      "id": "BK26-045",
      "client": "TBA",
      "eventName": "Calcutta",
      "date": "2026-10-03",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "D108"
    },
    {
      "id": "BK26-046",
      "client": "events@westernpower.com.au",
      "eventName": "Western Power Sundowner",
      "date": "2026-10-20",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 40,
      "start": "5:30 PM",
      "finish": "7:00 PM",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Janet Healy\n0400150705\nevents@westernpower.com.au\nLocation tbc\n40pax\n5:30pm - 7pm\nRaj catering\nBar Tab tbc",
      "contactEmail": "events@westernpower.com.au",
      "contactPhone": "0400150705",
      "sourceCell": "U108"
    },
    {
      "id": "BK26-047",
      "client": "nessaput@gmail.com",
      "eventName": "Venessa Putter Wedding",
      "date": "2026-10-24",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 40,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Venessa Putter\nWedding\nCozy rustic vibe\nApprox 40 people\nnessaput@gmail.com",
      "contactEmail": "nessaput@gmail.com",
      "contactPhone": "",
      "sourceCell": "Y108"
    },
    {
      "id": "BK26-048",
      "client": "TBA",
      "eventName": "Partyboss Halloween",
      "date": "2026-10-31",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AF108"
    },
    {
      "id": "BK26-049",
      "client": "TBA",
      "eventName": "Evolution Christmas Party",
      "date": "2026-11-20",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "U119"
    },
    {
      "id": "BK26-050",
      "client": "TBA",
      "eventName": "Evolution Christmas Party",
      "date": "2026-11-27",
      "roomId": "long-room",
      "roomName": "The Long Room",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AB119"
    },
    {
      "id": "BK26-051",
      "client": "TBA",
      "eventName": "Evolution Christmas Party",
      "date": "2026-11-20",
      "roomId": "old-bowling-lawn",
      "roomName": "The Old Bowling Lawn",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "U121"
    },
    {
      "id": "BK26-052",
      "client": "TBA",
      "eventName": "Evolution Christmas Party",
      "date": "2026-11-27",
      "roomId": "old-bowling-lawn",
      "roomName": "The Old Bowling Lawn",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AB121"
    },
    {
      "id": "BK26-053",
      "client": "TBA",
      "eventName": "Evolution Christmas Party",
      "date": "2026-11-20",
      "roomId": "library",
      "roomName": "Library",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "U122"
    },
    {
      "id": "BK26-054",
      "client": "TBA",
      "eventName": "Evolution Christmas Party",
      "date": "2026-11-27",
      "roomId": "library",
      "roomName": "Library",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AB122"
    },
    {
      "id": "BK26-055",
      "client": "brien@Stjohnwa.com.au",
      "eventName": "St Johns Xmas Party",
      "date": "2026-12-05",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 150,
      "start": "12:00 ",
      "finish": "3:00 ",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Daneka O’Brien\nSt John Ambulance\n0461 527 044\nDaneka.O’brien@Stjohnwa.com.au\n100-150 pax\n6:30pm - close\nMore details tbc\nInvoiced membership/venue hire - INV-1760",
      "contactEmail": "brien@Stjohnwa.com.au",
      "contactPhone": "0461 527 044",
      "sourceCell": "F128"
    },
    {
      "id": "BK26-056",
      "client": "TBA",
      "eventName": "Overland Xmas Party",
      "date": "2026-12-12",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "M128"
    },
    {
      "id": "BK26-057",
      "client": "TBA",
      "eventName": "XMAS DAY",
      "date": "2026-12-25",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "Z128"
    },
    {
      "id": "BK26-058",
      "client": "TBA",
      "eventName": "BOXING DAY",
      "date": "2026-12-26",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AA128"
    },
    {
      "id": "BK26-059",
      "client": "TBA",
      "eventName": "BOXING DAY PUBLIC HOLIDAY",
      "date": "2026-12-28",
      "roomId": "main-bar",
      "roomName": "Main Bar and Alfresco Area",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "AC128"
    },
    {
      "id": "BK26-060",
      "client": "TBA",
      "eventName": "Rema Tip Top Xmas",
      "date": "2026-12-04",
      "roomId": "old-bowling-lawn",
      "roomName": "The Old Bowling Lawn",
      "guests": 0,
      "start": "TBA",
      "finish": "TBA",
      "package": "From 2026 bookings spreadsheet",
      "catering": "See notes",
      "setup": "See spreadsheet notes",
      "staff": "Unassigned",
      "suppliers": "",
      "notes": "Imported from BOOKINGS_2026.xlsx",
      "contactEmail": "",
      "contactPhone": "",
      "sourceCell": "E131"
    }
  ],
  "availability": {
    "2026-02-26": {
      "main-bar": "Netball Sundowner"
    },
    "2026-03-05": {
      "main-bar": "Jeff Jones Wake"
    },
    "2026-03-07": {
      "main-bar": "Jessica & David Garwood"
    },
    "2026-03-17": {
      "main-bar": "St Patricks Day \nClubs function"
    },
    "2026-03-20": {
      "main-bar": "Meat raffle\nClubs function"
    },
    "2026-03-29": {
      "main-bar": "Goldifelds Footbal League Season Lauch - TBC"
    },
    "2026-03-15": {
      "long-room": "Raj Lunch"
    },
    "2026-03-12": {
      "billards-room": "Curtin University"
    },
    "2026-04-03": {
      "main-bar": "GOOD FRIDAY PUBLIC HOLIDAY"
    },
    "2026-04-06": {
      "main-bar": "EASTER MONDAY PUBLIC HOLIDAY"
    },
    "2026-04-12": {
      "main-bar": "Baby shower"
    },
    "2026-04-25": {
      "main-bar": "ANZAC DAY PUBLIC HOLIDAY"
    },
    "2026-04-29": {
      "long-room": "Restaurant booking - 25 pax"
    },
    "2026-05-08": {
      "main-bar": "Slade Hayward Wake"
    },
    "2026-05-20": {
      "main-bar": "KBCCI"
    },
    "2026-05-23": {
      "main-bar": "Night of the Muses"
    },
    "2026-05-24": {
      "main-bar": "Carmels 70th Birthday"
    },
    "2026-05-30": {
      "main-bar": "Veronica Lofthouse"
    },
    "2026-05-31": {
      "main-bar": "Hockey Club"
    },
    "2026-05-06": {
      "long-room": "Restaurant booking - Rotary Club - 20 pax"
    },
    "2026-05-10": {
      "long-room": "Ladies Brunch"
    },
    "2026-05-19": {
      "long-room": "Helloworld Info Night"
    },
    "2026-06-01": {
      "main-bar": "WA DAY PUBLIC HOLIDAY"
    },
    "2026-06-05": {
      "main-bar": "HC Open Night"
    },
    "2026-06-23": {
      "main-bar": "Helloworld"
    },
    "2026-06-27": {
      "main-bar": "Phils 60th birthday"
    },
    "2026-06-29": {
      "long-room": "Eastern Goldfields Auxiliary 60th Anniversary"
    },
    "2026-06-25": {
      "billards-room": "Chamber of Minerals & Energy"
    },
    "2026-06-30": {
      "billards-room": "RFDS"
    },
    "2026-07-01": {
      "main-bar": "Western Roads Sundowner"
    },
    "2026-07-17": {
      "main-bar": "KBCCI"
    },
    "2026-07-18": {
      "main-bar": "Jordan & Heidi's Wedding"
    },
    "2026-07-24": {
      "main-bar": "Kalsigns Xmas in July"
    },
    "2026-08-03": {
      "main-bar": "MACQUARIE Dinner"
    },
    "2026-08-04": {
      "main-bar": "Bell Potter",
      "long-room": "Wildcat Resources Lunch"
    },
    "2026-08-19": {
      "main-bar": "Gold/\nEsp Police",
      "long-room": "Gold/\nEsp Police"
    },
    "2026-08-20": {
      "main-bar": "KBCCI"
    },
    "2026-09-19": {
      "main-bar": "Kat O'Flaherty Birthday"
    },
    "2026-09-28": {
      "main-bar": "KINGS BIRTHDAY PUBLIC HOLIDAY"
    },
    "2026-09-30": {
      "main-bar": "The Round Inc"
    },
    "2026-10-03": {
      "main-bar": "Calcutta"
    },
    "2026-10-20": {
      "main-bar": "Western Power Sundowner"
    },
    "2026-10-24": {
      "main-bar": "Venessa Putter Wedding"
    },
    "2026-10-31": {
      "main-bar": "Partyboss Halloween"
    },
    "2026-11-20": {
      "long-room": "Evolution Christmas Party",
      "old-bowling-lawn": "Evolution Christmas Party"
    },
    "2026-11-27": {
      "long-room": "Evolution Christmas Party",
      "old-bowling-lawn": "Evolution Christmas Party"
    },
    "2026-12-05": {
      "main-bar": "St Johns Xmas Party"
    },
    "2026-12-12": {
      "main-bar": "Overland Xmas Party"
    },
    "2026-12-25": {
      "main-bar": "XMAS DAY"
    },
    "2026-12-26": {
      "main-bar": "BOXING DAY"
    },
    "2026-12-28": {
      "main-bar": "BOXING DAY PUBLIC HOLIDAY"
    },
    "2026-12-04": {
      "old-bowling-lawn": "Rema Tip Top Xmas"
    }
  }
};
